### ISSUE TITLE
Missing .svg files for County Down, Northern Ireland.

### ISSUE THREAD

**Issue by TheAlmightyDada** [HartBlanc/anki-uk-geography#1]
Hi there,

Thanks for this brilliant deck. I noticed that there are no map images for County Down, Northern Ireland.

I'm sure you would prefer to use your own, consistent image files but, just in case, I've attached the SVG files I created.

[HartBlanc_GitHub.zip](https://github.com/HartBlanc/anki-uk-geography/files/4809257/HartBlanc_GitHub.zip)

Thanks again.

**Comment by HartBlanc** [comment]
Hi @TheAlmightyDada 

Thanks for raising this issue.

I'm not 100% clear on where the problem is because the svg file for County Down can be found in [build/United Kingdom Geography - Regions Counties and Cities/media/c-County Down.svg](https://github.com/HartBlanc/anki-uk-geography/blob/master/build/United%20Kingdom%20Geography%20-%20Regions%20Counties%20and%20Cities/media/c-County%20Down.svg)

Also, when I search the following term in the Anki Card Browser and preview the card it appears to display correctly:
**"deck:United Kingdom Geography - Regions Counties and Cities" County Down**

This may have been an issue with an older version of the deck that has since been fixed, you could try re-downloading the deck from AnkiWeb. You shouldn't lose any of your progress if you just click through the field mappings without changing anything.

If that does not fix the issue, feel free to provide steps to produce a reproducible example and I'll see if I can get to the bottom of it.

**Comment by HartBlanc** [comment]
I'm going to mark this as closed for now as I haven't had an update in a while and it is not clear to me exactly what the issue is.

Feel free to raise again if you're still having a problem.
